version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 * * *"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    reviewers:
      - "agoodkind"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 * * *"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    reviewers:
      - "agoodkind"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 * * *"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    reviewers:
      - "agoodkind"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 * * *"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    reviewers:
      - "agoodkind"
