package ops

import (
	"context"
	"testing"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/s3"

	"goodkind.io/tack/internal/config"
	"goodkind.io/tack/internal/testenv"
)

// backupTestStore is a bucket of its own on the test SeaweedFS engine, the
// release production's object store runs. Tests set up and inspect it through
// the production S3 client and helpers.
type backupTestStore struct {
	t      *testing.T
	bucket testenv.ObjectStoreBucket
	client *s3.Client
	// stopped is true between stop and start.
	stopped bool
}

// newBackupTestStore creates an empty bucket and writes objects (key to body)
// into it.
func newBackupTestStore(t *testing.T, objects map[string][]byte) *backupTestStore {
	t.Helper()
	backupS3Attempts(t, backupS3DefaultMaxAttempts)
	store := &backupTestStore{t: t, bucket: testenv.ObjectStore(t), client: nil, stopped: false}
	store.client = newBackupS3Client(store.config())
	for key, body := range objects {
		store.put(key, body)
	}
	return store
}

// config returns a new config that reaches the bucket as the identity that
// may read and write it.
func (s *backupTestStore) config() *config.Config {
	return &config.Config{
		BackupS3Endpoint:   s.bucket.Endpoint,
		BackupS3AccessKey:  s.bucket.AccessKey, // gitleaks:allow key generated by the test engine
		BackupS3SecretKey:  s.bucket.SecretKey,
		BackupS3Region:     s.bucket.Region,
		BackupS3BucketMain: s.bucket.Bucket,
	}
}

// signAsReader switches cfg to the identity the engine lets read and list the
// bucket and refuses every write with AccessDenied.
func (s *backupTestStore) signAsReader(cfg *config.Config) {
	cfg.BackupS3AccessKey = s.bucket.ReadOnlyAccessKey // gitleaks:allow key generated by the test engine
	cfg.BackupS3SecretKey = s.bucket.ReadOnlySecretKey
}

// signAsWriter switches cfg back to the identity that may write.
func (s *backupTestStore) signAsWriter(cfg *config.Config) {
	cfg.BackupS3AccessKey = s.bucket.AccessKey // gitleaks:allow key generated by the test engine
	cfg.BackupS3SecretKey = s.bucket.SecretKey
}

// put writes body under key.
func (s *backupTestStore) put(key string, body []byte) {
	s.t.Helper()
	if err := putObjectBytes(context.Background(), s.client, s.bucket.Bucket, key, body); err != nil {
		s.t.Fatalf("put %s: %v", key, err)
	}
}

// remove deletes the object under key.
func (s *backupTestStore) remove(key string) {
	s.t.Helper()
	_, err := s.client.DeleteObject(context.Background(), &s3.DeleteObjectInput{
		Bucket: aws.String(s.bucket.Bucket),
		Key:    aws.String(key),
	})
	if err != nil {
		s.t.Fatalf("delete %s: %v", key, err)
	}
}

// object reads the object under key. found is false when the key is absent.
func (s *backupTestStore) object(key string) (body []byte, found bool) {
	s.t.Helper()
	body, err := getObjectBytes(context.Background(), s.client, s.bucket.Bucket, key)
	if isObjectNotFound(err) {
		return nil, false
	}
	if err != nil {
		s.t.Fatalf("get %s: %v", key, err)
	}
	return body, true
}

// stop stops the engine holding the bucket: its address refuses connections
// and the bucket stays on its disk. The caller defers ensureStarted, so the
// tests after it find the engine running.
func (s *backupTestStore) stop() {
	s.t.Helper()
	testenv.StopObjectStore(s.t, s.bucket.Container)
	s.stopped = true
	backupS3Attempts(s.t, 1)
}

// start starts the stopped engine again and returns the endpoint it answers
// on.
func (s *backupTestStore) start() string {
	s.t.Helper()
	s.bucket.Endpoint = testenv.StartObjectStore(s.t, s.bucket.Container)
	s.stopped = false
	backupS3Attempts(s.t, backupS3DefaultMaxAttempts)
	s.client = newBackupS3Client(s.config())
	return s.bucket.Endpoint
}

// ensureStarted starts the engine again if the test left it stopped.
func (s *backupTestStore) ensureStarted() {
	s.t.Helper()
	if s.stopped {
		s.start()
	}
}

// getBytes reads key through the production reader, so a missing key comes
// back as the error the engine answers with; it matches the getter the marker
// and version-log readers take.
func (s *backupTestStore) getBytes(key string) ([]byte, error) {
	return getObjectBytes(context.Background(), s.client, s.bucket.Bucket, key)
}

// putBytes writes key through the production writer; it matches the putter
// the marker and version-log writers take.
func (s *backupTestStore) putBytes(key string, body []byte) error {
	return putObjectBytes(context.Background(), s.client, s.bucket.Bucket, key, body)
}

// versionLogGetter is the production getter for the FoundationDB version
// record, bounded by the record's own read limit.
func (s *backupTestStore) versionLogGetter() func(key string) ([]byte, error) {
	return fdbVersionLogGetter(context.Background(), s.client, s.bucket.Bucket)
}
